### PR TITLE
README.md translated to Czech

### PR DESCRIPTION
**Pull request by ljanatka**
I'm not sure how You're gonna merge this so as a first translation attempt I only translated the README.md.
If anything else is needed, please let me know.

### CODE REVIEW

**Comment by russmiles** [comment]
Thanks so much for this PR! Would you mind migrating the text into a second README file, perhaps with the name README_cz.md or something similar? 

Also the wording in the Principles of Chaos has changed, removing the "distributed" classifier in the quote, can you reflect that in the translation as well?

Finally if you could squash the PR into one candidate commit for review and then merge, we will be good to go! Thanks again so much for this!

**Comment by ljanatka** [comment]
I managed to squash the commits, but only in a new branch. Sorry, I really am not a "git master" :-). Please check the other pull request and if it is OK, I will close this one ...

**Comment by ljanatka** [comment]
Merged from other pull request, closing this one

**Comment by russmiles** [comment]
Everything is great in the other branch, closing this PR.

**Pull request closed without merging**
